### ISSUE TITLE
choosing DSARR as the default skin before DnD of archetypes gives empty space

### ISSUE THREAD

**Issue by gonuke** [cyclus/cyclist2#58]
I set the skin to DSARR before dragging any archetypes into the pane and it appeared as though nothing happened.  When I toggled back to default/DSARR again, it came back fine.

**Comment by FlanFlanagan** [comment]
This appears to be happening because some prototypes do not have appropriate niches until the a skin is selected after the prototype is placed. For example it is fine to switch to DSARR and then DnD a reactor, but not a separations facility.

**Comment by gidden** [comment]
Does a niche get added then when the original skin is used to DnD? Could
that be done before DnDing?

On Mon, Jun 1, 2015 at 1:14 PM, FlanFlanagan <notifications@github.com>
wrote:

> This appears to be happening because some prototypes do not have
> appropriate niches until the a skin is selected after the prototype is
> placed. For example it is fine to switch to DSARR and then DnD a reactor,
> but not a separations facility.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclist2/issues/58#issuecomment-107659296>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by FlanFlanagan** [comment]
I can be done before. I never ran into this problem (since some of them work I never noticed the issue). What is missing is if the facility doesn't have a niche that matches a niche in the skin set it needs to take the generic "facility" niche.

**Comment by FlanFlanagan** [comment]
It*

**Comment by gidden** [comment]
Ok, if you point me to a line, I can fix it immediately. Otherwise it might
take me a while..

On Mon, Jun 1, 2015 at 3:29 PM, FlanFlanagan <notifications@github.com>
wrote:

> It*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclist2/issues/58#issuecomment-107697224>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by FlanFlanagan** [comment]
line 284 of CycIC.java

facility.cycicCircle.image.setImage(DataArrays.visualizationSkins.get(i).images.get(facility.niche));

Basically what needs to happen is a check to see if the niche exists in the images key set. Which can be accessed most easily with
 
images.keySet().toArray();

If it passes then take that value otherwise take the map key "facility"

**Comment by gonuke** [comment]
Fixed in #59 or sooner
